let SPECIAL_SEARCH_NAME = [
  "deoxys-normal",
  "wormadam-plant",
  "giratina-altered",
  "shaymin-land",
  "basculin-red-striped",
  "darmanitan-standard",
  "tornadus-incarnate",
  "thundurus-incarnate",
  "landorus-incarnate",
  "keldeo-ordinary",
  "meloetta-aria",
  "meowstic-male",
  "aegislash-shield",
  "pumpkaboo-average",
  "gourgeist-average",
  "oricorio-baile",
  "lycanroc-midday",
  "wishiwashi-solo",
  "minior-red-meteor",
  "mimikyu-disguised",
  "toxtricity-amped",
  "eiscue-ice",
  "indeedee-male",
  "zacian-hero",
  "zamazenta-hero",
  "urshifu-single-strike",
];

export default SPECIAL_SEARCH_NAME;
